if (NOT PREFIX)
    set(PREFIX "UWF")
endif ()
if (NOT FALLBACK_VERSION)
    set(FALLBACK_VERSION "1.0.0.0")
endif ()
if (NOT OUTPUT_FILE)
    message(FATAL_ERROR "GenerateGitVersion: OUTPUT_FILE is required")
endif ()
if (NOT SOURCE_DIR)
    set(SOURCE_DIR "${CMAKE_SOURCE_DIR}")
endif ()

function(parse_numeric_version version out_major out_minor out_patch out_build)
    if (NOT version MATCHES "^([0-9]+)\.([0-9]+)\.([0-9]+)(\.([0-9]+))?$")
        message(FATAL_ERROR "GenerateGitVersion: version must be a.b.c or a.b.c.d, got '${version}'")
    endif ()
    set(${out_major} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    set(${out_minor} "${CMAKE_MATCH_2}" PARENT_SCOPE)
    set(${out_patch} "${CMAKE_MATCH_3}" PARENT_SCOPE)
    if (CMAKE_MATCH_5 STREQUAL "")
        set(${out_build} 0 PARENT_SCOPE)
    else ()
        set(${out_build} "${CMAKE_MATCH_5}" PARENT_SCOPE)
    endif ()
endfunction()

parse_numeric_version("${FALLBACK_VERSION}" _v_major _v_minor _v_patch _v_build)
set(_ver_string "${FALLBACK_VERSION}")

if (GIT_EXECUTABLE AND EXISTS "${GIT_EXECUTABLE}")
    execute_process(
            COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" describe
                    --tags --long --always --dirty --first-parent
                    --match "[0-9]*" --match "v[0-9]*"
            RESULT_VARIABLE _describe_result
            OUTPUT_VARIABLE _describe
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    if (_describe_result EQUAL 0 AND
            _describe MATCHES "^v?([0-9]+)\.([0-9]+)\.([0-9]+)(\.([0-9]+))?-([0-9]+)-g([0-9a-fA-F]+)(-dirty)?$")
        set(_v_major "${CMAKE_MATCH_1}")
        set(_v_minor "${CMAKE_MATCH_2}")
        set(_v_patch "${CMAKE_MATCH_3}")
        set(_tag_build "${CMAKE_MATCH_5}")
        set(_distance "${CMAKE_MATCH_6}")
        set(_short_sha "${CMAKE_MATCH_7}")
        set(_dirty "${CMAKE_MATCH_8}")

        set(_tag_version "${_v_major}.${_v_minor}.${_v_patch}")
        if (NOT _tag_build STREQUAL "")
            string(APPEND _tag_version ".${_tag_build}")
        else ()
            set(_tag_build 0)
        endif ()

        # Windows VERSIONINFO 只能使用四段数字。第四段在标签的第四段基础上
        # 加上标签后的提交数；后续统一使用三段发布标签时，它就是自然递增的
        # commit distance。
        math(EXPR _v_build "${_tag_build} + ${_distance}")

        if (_distance EQUAL 0)
            set(_ver_string "${_tag_version}")
        else ()
            set(_ver_string "${_tag_version}+${_distance}.g${_short_sha}")
        endif ()
        if (_dirty)
            string(APPEND _ver_string ".dirty")
        endif ()
    elseif (_describe_result EQUAL 0 AND _describe MATCHES "^([0-9a-fA-F]+)(-dirty)?$")
        # 仓库还没有数字标签：以回退版本为基准，用全仓库提交数提供递增量。
        set(_short_sha "${CMAKE_MATCH_1}")
        set(_dirty "${CMAKE_MATCH_2}")
        execute_process(
                COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-list --count HEAD
                RESULT_VARIABLE _count_result
                OUTPUT_VARIABLE _commit_count
                ERROR_QUIET
                OUTPUT_STRIP_TRAILING_WHITESPACE
        )
        if (_count_result EQUAL 0 AND _commit_count MATCHES "^[0-9]+$")
            math(EXPR _v_build "${_v_build} + ${_commit_count}")
            set(_ver_string "${FALLBACK_VERSION}+${_commit_count}.g${_short_sha}")
            if (_dirty)
                string(APPEND _ver_string ".dirty")
            endif ()
        endif ()
    endif ()
endif ()

foreach (_part IN ITEMS _v_major _v_minor _v_patch _v_build)
    if (${_part} GREATER 65535)
        message(FATAL_ERROR "GenerateGitVersion: Windows version component ${${_part}} exceeds 65535")
    endif ()
endforeach ()

set(_content "#pragma once

// Generated by cmake/GenerateGitVersion.cmake at build time. Do not edit.

#define ${PREFIX}_VER_MAJOR    ${_v_major}
#define ${PREFIX}_VER_MINOR    ${_v_minor}
#define ${PREFIX}_VER_PATCH    ${_v_patch}
#define ${PREFIX}_VER_BUILD    ${_v_build}
#define ${PREFIX}_VER_STRING   \"${_ver_string}\"
")

get_filename_component(_output_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_dir}")
set(_old_content "")
if (EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _old_content)
endif ()
if (NOT _old_content STREQUAL _content)
    file(WRITE "${OUTPUT_FILE}" "${_content}")
endif ()

if (NOT QUIET)
    message(STATUS "Git version: ${_ver_string} (${_v_major}.${_v_minor}.${_v_patch}.${_v_build})")
endif ()
